fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

tdt_demo:
    resource: "@TDTDemoBundle/Resources/config/routing.yml"

smart_media:
    resource: "@SmartMediaBundle/Resources/config/routing.yml"

tdt_site:
    resource: "@TDTSiteBundle/Resources/config/routing.yml"

smart_blog_admin_article:
    resource: "@SmartBlogBundle/Resources/config/routing_admin_article.yml"
    prefix:   /admin/blog/article/

smart_blog_admin_category:
    resource: "@SmartBlogBundle/Resources/config/routing_admin_category.yml"
    prefix:   /admin/blog/category/

smart_blog_admin_tag:
    resource: "@SmartBlogBundle/Resources/config/routing_admin_tag.yml"
    prefix:   /admin/blog/tag/

smart_texter:
    resource: "@SmartTexterBundle/Resources/config/routing_admin.yml"
    prefix:   /admin/texter/

tdt_blog:
    resource: "@TDTBlogBundle/Resources/config/routing.yml"
    prefix:   /blog/

tdt_news:
    resource: "@TDTNewsBundle/Resources/config/routing.yml"
    prefix:   /news/

tdt_news_admin:
    resource: "@TDTNewsBundle/Resources/config/routing_admin.yml"
    prefix:   /admin/news/

smart_gallery:
    resource: "@SmartGalleryBundle/Resources/config/routing.yml"
    prefix:   /gallery/

tdt_user:
    resource: "@TDTUserBundle/Resources/config/routing.yml"

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
