smart_blog_index:
    path: /
    defaults: { _controller: SmartBlogBundle:Article:page }

smart_blog_article:
    path: /{slug}.html
    defaults: { _controller: SmartBlogBundle:Article:show }

smart_blog_article_edit:
    path: /edit/{id}/
    defaults: { _controller: SmartBlogBundle:Article:edit }
    requirements:
        id: \d+

smart_blog_page_index:
    path: /page/
    defaults: { _controller: SmartBlogBundle:Article:page }

smart_blog_page:
    path: /page/{page}/
    defaults: { _controller: SmartBlogBundle:Article:page }

smart_blog_category:
    path: /category/{slug}/
    defaults: { _controller: SmartBlogBundle:Default:index }

#smart_blog_category_page:
#    path: /category/{slug}/page/{page_num}/
#    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_tag_index:
    path: /tag/
    defaults: { _controller: SmartBlogBundle:Tag:index }

smart_blog_tag:
    path: /tag/{slug}/
    defaults: { _controller: SmartBlogBundle:Tag:showArticles }

smart_blog_archive_yearly:
    path: /archive/{year}/
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_archive_monthly:
    path: /archive/{year}/{month}/
    defaults: { _controller: SmartBlogBundle:Default:index }

smart_blog_archive_dayly:
    path: /archive/{year}/{month}/{day}/
    defaults: { _controller: SmartBlogBundle:Default:index }

#smart_blog_admin:
#    resource: "@SmartBlogBundle/Resources/config/routing_admin.yml"
#    prefix: /admin/
